name: 'Realtime DB Action'
description: 'Connect as admin and execute commands in firebase realtime database'
icon: database
inputs:
  project_id:
    description: 'Project id'
    required: true
  private_key_id:
    description: 'Private Key Id'
    required: true
  private_key:
    description: 'Private Key'
    required: true
  client_email:
    description: 'Client Email'
    required: true
  client_id:
    description: 'Client Id'
    required: true
  auth_uri:
    description: 'Auth URI'
    required: true
  token_uri:
    description: 'Token URI'
    required: true
  auth_provider_x509_cert_url:
    description: 'Auth Provider x509 Cert URL'
    required: true
  client_x509_cert_url:
    description: 'Client x509 Cert URL'
    required: true
  database_default_url:
    description: 'URL to connect in default database'
    required: true
  reference:
    description: 'Reference to access in database'
    required: true
  operation:
    description: 'The operation to be performed, which can be get or set'
    required: true
  data:
    description: 'New data that will be used to update the reference'
outputs:
  result:
    description: 'Result data from get operation execution'
runs:
  using: 'node16'
  main: 'src/index.js'
    
  
