name: Test Realtime Firebase
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test get
        uses: rafacolab/realtime-db-action@v1.0.0
        id: testGet
        with:
          project_id: ${secrets.project_id}
          private_key_id: ${secrets.private_key_id}
          private_key: ${secrets.private_key}
          client_email: ${secrets.client_email}
          client_id: ${secrets.client_id}
          auth_uri: ${secrets.auth_uri}
          token_uri: ${secrets.token_url}
          auth_provider_x509_cert_url: ${secrets.auth_provider_x509_cert_url}
          client_x509_cert_url: ${secrets.client_x509_cert_url}
          database_default_url: ${secrets.database_default_url}
          reference: '/test/user'
          operation: get
      - name: Get the output
        run: echo "De object result is ${{ steps.testGet.outputs.RESULT }}"
      - name: test set
        uses: rafacolab/realtime-db-action@v1.0.0
        with:
          project_id: ${secrets.project_id}
          private_key_id: ${secrets.private_key_id}
          private_key: ${secrets.private_key}
          client_email: ${secrets.client_email}
          client_id: ${secrets.client_id}
          auth_uri: ${secrets.auth_uri}
          token_uri: ${secrets.token_url}
          auth_provider_x509_cert_url: ${secrets.auth_provider_x509_cert_url}
          client_x509_cert_url: ${secrets.client_x509_cert_url}
          reference: '/test/user'
          database_default_url: ${secrets.database_default_url}
          operation: set
          data: "{ \"name\": \"Rafael de França Neves\", \"age\": 41 }"
