name: Test Realtime Firebase
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test set
        uses: rafacolab/realtime-db-action@v1.0.6
        with:
          project_id: "kodizn"
          private_key_id: "257299d5d3bc3226b38471891f2d8c75c8895d28"
          private_key: "${{secrets.PRIVATE_KEY_TEST}}"
          client_email: "firebase-adminsdk-837nd@kodizn.iam.gserviceaccount.com"
          client_id: "115581378269331779838"
          auth_uri: "https://accounts.google.com/o/oauth2/auth"
          token_uri: "https://oauth2.googleapis.com/token"
          auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
          client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-837nd%40kodizn.iam.gserviceaccount.com"
          reference: '/test/user'
          DATA: "{ \"name\": \"Rafael Neves\", \"age\": 41 }"
          operation: set
      - name: test get
        uses: rafacolab/realtime-db-action@v1.0.6
        id: testGet
        with:
          project_id: "kodizn"
          private_key_id: "257299d5d3bc3226b38471891f2d8c75c8895d28"
          private_key: "${{secrets.PRIVATE_KEY_TEST}}"
          client_email: "firebase-adminsdk-837nd@kodizn.iam.gserviceaccount.com"
          client_id: "115581378269331779838"
          auth_uri: "https://accounts.google.com/o/oauth2/auth"
          token_uri: "https://oauth2.googleapis.com/token"
          auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
          client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-837nd%40kodizn.iam.gserviceaccount.com"
          reference: '/test/user'
          operation: get
      - name: Get the output time
        run: echo "The time was ${{ steps.testGet.outputs.RESULT }}"
